add layout and some changes in app.js
petteri-te/github-exercise pull request #5
Opened 2023-10-06 12:58 UTC by shardendu-design

Layout added and some changes in app.js.

2023-10-09 07:35 UTC, petteri-te reviewed
just comment

2023-10-09 07:48 UTC, petteri-te requested changes
please resolve the conflicts

2023-10-10 09:51 UTC, petteri-te approved these changes
👍

2023-10-11 12:20 UTC, petlappa commented
closing PR. I will try to remove teh app-cache from the repo

2023-10-11 12:20 UTC, closed without merging